### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by VJ-Ulaganathan** [PhongCode/Facebook-Image-Backup#1]
Please suggest a fix for running this script on a non Windows environment (Debian). Thank you.

I get the following error:--

```
Traceback (most recent call last):
  File "app.py", line 16, in <module>
    ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myapp_id)
AttributeError: module 'ctypes' has no attribute 'windll'
```

**Comment by PhongCode** [comment]
Hi @VJ-Ulaganathan,
This script used to make *.exe file with **pyinstaller** on windows (the option). Just comment this script if you don't need it.

**Comment by PhongCode** [comment]
Hi @VJ-Ulaganathan ,
This script used to make *.exe file with pyinstaller on windows (the option). Just comment or delete this script if you don't need it.
