### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by lanzjose** [PhongCode/Facebook-Image-Backup#3]
Edited because it was my mistake. I commented on the wrong Github

**Comment by mrtrieuphong** [comment]
Hi @unmystic666 do you have any proof? This is open source, you can see anything before run. If something is vulnerable, make sure you don't install libraries from unknown sources.

**Comment by lanzjose** [comment]
> Hi @unmystic666 do you have any proof? This is open source, you can see anything before run. If something is vulnerable, make sure you don't install libraries from unknown sources.

I am EXTREMELY sorry.
This wasn't the app I wanted to report! I commented on the wrong Github. This one is 100% clean.
Sorry
